### ISSUE TITLE
betrokkene moet tegelijkertijd een http://www.w3.org/ns/regorg#RegisteredOrganization en een https://data.vlaanderen.be/ns/persoon#GeregistreerdPersoon zijn. Is dit de bedoeling?

### ISSUE THREAD

**Issue by gezever** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#10]
de constructie met die betrokkene die een persoon of een organisatie is, geeft een fout
Shacl
@prefix shacl: <http://www.w3.org/ns/shacl#> .

<https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap> <https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-apshapes> 
    <https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap#GepleegdFeitShape>.

<https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap#GepleegdFeitShape> a shacl:NodeShape;
  shacl:closed false;
  shacl:property [
    shacl:class <http://www.w3.org/ns/regorg#RegisteredOrganization>;
    shacl:description "De Geregistreerde Organisatie die het feit gepleegd heeft.";
    shacl:maxCount 1;
    shacl:name "betrokkene";
    shacl:path <https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene>
  ], [
    shacl:class <https://data.vlaanderen.be/ns/persoon#GeregistreerdPersoon>;
    shacl:description "De Geregistreerde Persoon die het feit gepleegd heeft.";
    shacl:maxCount 1;
    shacl:name "betrokkene";
    shacl:path <https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene>
  ];
  shacl:targetClass <https://data.vlaanderen.be/ns/bestuurlijke-sancties#GepleegdFeit> .

data

<https://data.vlaanderen.be/id/gepleedfeit/1> a <https://data.vlaanderen.be/ns/bestuurlijke-sancties#GepleegdFeit> ;
<https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene> <https://data.vlaanderen.be/id/persoon/1> .

<https://data.vlaanderen.be/id/persoon/1> a <https://data.vlaanderen.be/ns/persoon#GeregistreerdPersoon> .

resultaat
$ shacl validate --shapes bestuurlijk-sanctieregister-ap-SHACL-1.ttl --data GepleegdFeit-persoon.ttl 
@prefix shacl: <http://www.w3.org/ns/shacl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .

[ a            sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  <https://data.vlaanderen.be/id/gepleedfeit/1> ;
                 sh:resultMessage              "ClassConstraint[<http://www.w3.org/ns/regorg#RegisteredOrganization>]: Expected class :<http://www.w3.org/ns/regorg#RegisteredOrganization> for <https://data.vlaanderen.be/id/persoon/1>" ;
                 sh:resultPath                 <https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene> ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:ClassConstraintComponent ;
                 sh:sourceShape                []  ;
                 sh:value                      <https://data.vlaanderen.be/id/persoon/1>
               ]
] .

**Comment by gezever** [comment]
shape
@prefix shacl: <http://www.w3.org/ns/shacl#> .

<https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap> <https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-apshapes> 
    <https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap#GepleegdFeitShape>.


<https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap#GepleegdFeitShape> a shacl:NodeShape;
  shacl:closed false;
  shacl:property [
    shacl:class <http://www.w3.org/ns/regorg#RegisteredOrganization>;
    shacl:description "De Geregistreerde Organisatie die het feit gepleegd heeft.";
    shacl:maxCount 1;
    shacl:name "betrokkene";
    shacl:path <https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene>
  ], [
    shacl:class <https://data.vlaanderen.be/ns/persoon#GeregistreerdPersoon>;
    shacl:description "De Geregistreerde Persoon die het feit gepleegd heeft.";
    shacl:maxCount 1;
    shacl:name "betrokkene";
    shacl:path <https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene>
  ];
  shacl:targetClass <https://data.vlaanderen.be/ns/bestuurlijke-sancties#GepleegdFeit> .

data

<https://data.vlaanderen.be/id/gepleedfeit/1> a <https://data.vlaanderen.be/ns/bestuurlijke-sancties#GepleegdFeit> ;
<https://data.vlaanderen.be/ns/bestuurlijke-sancties#betrokkene> <https://data.vlaanderen.be/id/persoon/1> .

<https://data.vlaanderen.be/id/persoon/1> a <https://data.vlaanderen.be/ns/persoon#GeregistreerdPersoon> , <http://www.w3.org/ns/regorg#RegisteredOrganization>.

result
p$ shacl validate --shapes bestuurlijk-sanctieregister-ap-SHACL-1.ttl --data GepleegdFeit-persoon.ttl 
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .

[ a            sh:ValidationReport ;
  sh:conforms  true
] .

**Comment by gezever** [comment]
@Vigetorix 
Een manier om correct een keuze uit te drukken in een uml klassediagram is een abstracte klasse (vb. prov:Agent) met twee subklassen http://www.w3.org/ns/regorg#RegisteredOrganization en  https://data.vlaanderen.be/ns/persoon#GeregistreerdPersoon
De fixen die je hebt gedaan, worden die gepubliceerd, zodat we die kunnen bekijken aub?
Vriendelijke groeten

**Comment by Vigetorix** [comment]
Beste Geert, 

De aanpassing met Persoon en GeregistreerdeOrganisatie als subklassen van prov:Agent zijn doorgevoerd in de laatste commit. Kan je deze even bekijken?

**Comment by gezever** [comment]
@Vigetorix 
Ik sluit deze issue, is opgelost.
Opmerking: De nieuwe shacl nodeshape GeregistreerdPersoonShape erft wel niet over van Persoon
