### ISSUE TITLE
GepleegdFeit

### ISSUE THREAD

**Issue by Stvngrnrt** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#11]
De term 'GepleegdFeit' mist wat nuance qua taalgebruik: het gaat er bij voorbaat vanuit dat het feit 'gepleegd' is en de beschuldiging maw terecht is bij opname in het sanctieregister, terwijl vrijspraak via procedure nog steeds perfect mogelijk is. Beter lijkt iets in de trant van 'VastgesteldFeit': een term waarbij voorafname van schuld niet impliciet vervat zit.

**Comment by philipperutten** [comment]
Op zijn minst is verheldering nodig rond deze nuance.
Bijvoorbeeld ook: wanneer een geldsom wordt betaalt (in feite om de vervolging af te komen), geldt dat dan wél als schuldbekentenis voor de veronderstelde overtreding?

**Comment by michiellefever1** [comment]
•	Gepleegdfeit wordt hernoemd naar ‘Feit’.

**Comment by vlavaert** [comment]
Waarom wordt in het sanctiedossier/-register niet "vervolgd feit" gebruikt, zoals in VHP?
