### ISSUE TITLE
VervalSanctiemogelijkheidDoorBetalingGeldsom ook van toepassing voor Beboetingsinstantie

### ISSUE THREAD

**Issue by Stvngrnrt** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#12]
Bij administratieve boetes uitgedeeld door Dierenwelzijn (de beboetingsinstantie), wordt aan de betrokkene gevraagd een geldsom te betalen; indien betaald wordt, wordt de zaak niet overgemaakt aan het parket (de vervolginginstantie), anders wel (eigenlijk een soort van minnelijke schikking dus, al mag die term hier niet gebruikt worden).

Echter: in het datamodel staat 'Verval van de Sanctiemogelijkheid door Betaling van een Geldsom' enkel vermeld als mogelijk uit een Beslissing tot Bestuurlijke Vervolging (specifiëring van een Beslissing van een Vervolginstantie); maar hier gaat het dus een beslissing van een Beboetingsinstantie, wat niet is toegelaten binnen huidig voorstel van het model.

Het lijkt ons handiger om in het model de types beslissing rechtstreeks te hangen aan BestuurlijkeBeslissing, en de vraag wie welke beslissing mag nemen niet via het model op te leggen (dat kan desnoods via rules). Daarmee zou bovenstaand euvel dan ook meteen verholpen zijn.

**Comment by michiellefever1** [comment]
•	Akkoord om alle types bestuurlijke beslissingen meteen onder te brengen onder BestuurlijkeBeslissing
•	Sepot eruit halen want geen onderdeel van SanctieRegister.
