### ISSUE TITLE
Cardinaliteit tussen GepleegdFeit en GeregistreerdPersoon moet ruimer

### ISSUE THREAD

**Issue by Stvngrnrt** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#13]
Een vastgesteld feit kan op meerdere personen slaan die het gepleegd hebben. Cardinaliteit 0...1 lijkt dus incorrect; correcter lijkt 0...* en daartussen heb je nog de toerekenbaarheid van elke persoon aan het feit. Waarbij oa kan gekeken worden naar de betrokkenheid van de verschillende daders.

**Comment by philipperutten** [comment]
Bijvoorbeeld, uit het kaderdecreet: "De bestuurlijke sanctie kan worden opgelegd aan diegene die het misdrijf of de inbreuk heeft uitgevoerd, er opdracht toe heeft gegeven of er zijn medewerking aan heeft verleend."

**Comment by michiellefever1** [comment]
•	De definitie van ‘Feit’ heeft hier betrekking op een vervolgingsbeslissing.
•	Indien meerdere personen betrokken zijn, wordt voor elk van deze personen een ‘Feit met een beslissing aangemaakt.
•	Er moet XOR staan tussen ‘Persoon’ en ‘Organisatie’.
