### ISSUE TITLE
Geen directe link tussen persoon en sanctie

### ISSUE THREAD

**Issue by Stvngrnrt** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#14]
We missen een directe link tussen persoon en sanctie:, in dit applicatieprofiel is de link enkel onrechtstreeks gemaakt via GepleegdFeit (waarop nog de vrijspraak kan komen; of dat ook aanleiding kan geven tot meerdere sancties) & BestuurlijkeBeslissing, waardoor niet rechtstreeks kan uitgemaakt worden hoeveel sancties een persoon heeft gekregen.

**Comment by michiellefever1** [comment]
•	In VHP is er een bestuurlijke beslissing die betrekking heeft op feiten die door een persoon gepleegd zijn. Er is geen rechtstreeks verband tussen persoon en sanctie in het datamodel.
•	Je kan het onrechtstreeks afleiden, maar er is een rechtstreeks verband.
•	We kiezen voor model; onrechtstreeks verband bestaat en houdt stand.
