### ISSUE TITLE
Sancties niet alleen voor geregistreerde personen

### ISSUE THREAD

**Issue by Stvngrnrt** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#15]
Boetes (voor bv dierenmishandeling) kunnen ook worden opgelegd aan mensen die niet geïdentificeerd zijn via het rijksregister of een buitenlands equivalent (bv mensen zonder papieren kunnen ook beboet worden). Het huidige voorstel van het model linkt gepleegde feiten echter enkel aan geregistreerde personen, wat dus niet correct is.

**Comment by michiellefever1** [comment]
•	Het wordt aangepast tot ‘Persoon’, en GeregistreerdPersoon is daar onderdeel van. 
•	Idem ‘Organisatie.’
