### ISSUE TITLE
rechtsnorm

### ISSUE THREAD

**Issue by philipperutten** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#16]
Een "gepleegd feit" overtreedt, volgens het model, een "rechtsbrononderdeel".

Is hier "rechts**norm**" niet een geschiktere term (of geschikter concept)?

Het kaderdecreet spreekt van "feiten die strijdig zijn met de Vlaamse regelgeving", en definieert die laatste als "normen [...]".

De "rechtsbron" --en daarmee ook een eventueel "rechtsbrononderdeel", voor zover dat slaat op, bijvoorbeeld, een artikel-- duidt eerder op de _plaats_ waar de rechtsnorm in kwestie is vastgelegd.

Kortom: gepleegd feit F vormt een overtreding op norm N die in rechtsbron/rechtsbrononderdeel R is vastgelegd.

NB: volgens diezelfde redenering werd jaren geleden ook voor een toepassing op gebied van bestuurlijke sanctionering binnen het departement LNE (nu Omgeving) ervoor gekozen de term norm te hanteren.

**Comment by michiellefever1** [comment]
De aanduiding ‘rechtsbrononderdeel’ wordt behouden,gezien het ook als dusdanig in het OSLO model van Vlaamse Codex staat.
