### ISSUE TITLE
relatie tussen beslissing en feitomschrijving

### ISSUE THREAD

**Issue by philipperutten** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#17]
Vaak maakt de feitenomschrijving integraal onderdeel uit van de beslissing.
Bijvoorbeeld: feiten worden een eerste maal vastgesteld door een agent en vastgelegd in een PV. Dit PV komt terecht bij de afdeling handhaving van het departement omgeving voor bestuurlijk sanctionering, die de feiten verder onderzoekt (schriftelijk verweer, hoorzittingen...) en mogelijk nieuwe vaststellingen doet en tot een nieuwe 'versie' van de feiten komt, die dan, samen met de bijhorende boete, in de boetebeslissing wordt vastgelegd. De beslissing gaat dan niet "over" gepleegde feiten, maar ze **bepaalt** deze.

**Comment by michiellefever1** [comment]
•	GepleegdFeit wordt ‘Feit’
•	Relatie tussen Beslissing en Feit zal aangepast worden met aanduiding dat de relatie deel uitmaakt van een beslissing. Een feit kan niet bestaan als ze niet in een beslissing opgenomen is.
