### ISSUE TITLE
beslissing genereert stuk

### ISSUE THREAD

**Issue by philipperutten** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#18]
Van het beslissingsproces kun je zeggen dat het een stuk genereert, maar zijn we in deze context niet eerder geïnteresseerd in  het product van het beslissingsproces, zijnde **de beslissing zelf**---die niet een stuk **genereert**, maar hierin zijn neerslag vindt? 

Misschien is hier ook aansluiting aangewezen bij het begrip "besluit" (https://data.vlaanderen.be/ns/besluit#Besluit)

**Comment by michiellefever1** [comment]
•	De relatie tussen beslissing en stuk zal hernoemd worden naar “vindt zijn neerslag in”.
•	Concept “Besluit” willen we niet hanteren ipv Beslissing, want niet elke beslissing is een besluit. Een besluit is voor VHP niet voldoende; niet elke beslissing is een besluit.
•	Beslissingsactiviteit “genomen door” mag weggehaald worden.
