### ISSUE TITLE
aanvullende sanctie vereist hoofdsanctie

### ISSUE THREAD

**Issue by philipperutten** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#19]
als het inderdaad zo is dat de sancties vermeld onder "aanvullende sanctie" enkel en alleen kunnen worden opgelegd in combinatie met een bestuurlijke geldboete (uit het kaderdecreet kan ik dat overigens niet opmaken, noch uit andere regelgeving, maar misschien mis ik iets) dan lijkt me dat in ieder geval eerder een business regel dan een eigenschap van de zogenaamde aanvullende sanctie

**Comment by michiellefever1** [comment]
Onderscheid tussen aanvullende sanctie en hoofdsanctie zal verdwijnen.
