### ISSUE TITLE
alternatieve sanctie vs hoofdsanctie vs aanvullende sanctie

### ISSUE THREAD

**Issue by philipperutten** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#20]
Wat is de meerwaarde van deze onderverdeling/subklassering?
Komt dit voort uit regelgeving? In het kader decreet komen deze termen alleszins niet voor.

Wel is er sprake van een "alternatieve bestuurlijke geldboete", waar het aspect "alternatief" slaat op het feit dat de bestuurlijke geldboete geldt als "alternatief" voor de strafrechtelijke sanctionering die voor misdrijven in principe de eerste weg is (in tegenstelling tot de "exclusieve bestuurlijke geldboete" voor inbeuken, waar "exclusief" slaat op het feit dat inbreuken zuiver bestuurlijke schendingen inhouden waarvoor geen strafrechtelijke vervolging geldt en de bestuurlijk sanctionering derhalve de enige (exclusieve) weg is. 

Een (alternatieve) bestuurlijk geldboete is in het model onder hoofdsanctie ingedeeld, terwijl het formeel toch eigenlijk een alternatieve sanctie heet te zijn. Hier wringt deze subklassering dus.

In welke mate bovengenoemde formele betekenis van de term "alternatief" ook slaat op de soorten sancties die onder de "alternatieveSanctieType" worden opgelijst is mij niet duidelijk.

Tevens merk ik op dat de verschillende soorten sancties onder de "alternatieve sanctie" 'slechts' een type veld zijn, terwijl de andere soorten sancties met een eigen subklasse worden gerepresenteerd --dit lijkt niet consistent.

Mogelijk te overwegen alternatief: elke soort sanctie zijn eigen klasse met eigen eigenschappen, en deze allemaal als directe subklasse van de generalisatie-klasse "bestuurlijke sanctie".

**Comment by michiellefever1** [comment]
•	Met alternatieve sanctie wordt hier een alternatief van een bestuurlijke sanctie (op bestuurlijk niveau bedoeld). Het betreft dus niét een bestuurlijke sanctie als alternatief voor een strafrechtelijke sanctie.
•	Vanuit het auteurs-team is men akkoord om ‘alternatieve sanctie’ te schrappen uit het Applicatieprofiel gezien deze niet meer opgenomen is in het kaderdecreet.
•	Beslissing alternatieve procedure zal ook geschrapt worden.
•	Onderscheid tussen aanvullende sanctie en hoofdsanctie zal ook verdwijnen
•	Bestuurlijke sanctie zal bestaan uit
o	Uitsluiting van steun
o	Verbeurdverklaring
o	Bestuurlijke geldboete
