### ISSUE TITLE
Dead link 

### ISSUE THREAD

**Issue by samuvack** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#21]
dead link: [Vocabularium](https://data.vlaanderen.be/ns/bestuurlijk-sanctieregister)

**Comment by Vigetorix** [comment]
Dag Samuel, de link naar het laatste vocabularium kan je hier vinden: 
https://data.vlaanderen.be/doc/vocabularium/bestuurlijke-sancties/kandidaatstandaard/2022-06-23/
