### ISSUE TITLE
ih model niets rond vaststellen van feiten

### ISSUE THREAD

**Issue by Stvngrnrt** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#4]
We missen bij GepleegdFeit informatie rond hoe en door wie dit is vastgesteld; bv als dit door politie gebeurt is dit met een pv. Ook het onderzoek dat volgt uit de feiten is belangrijk en lijkt volledig te ontbreken in het model.

**Comment by michiellefever1** [comment]
•	Onderzoek, vaststellen van feiten is out of scope voor het Sanctieregister. In het kader van bestuurlijke handhaving (en het Vlaams Handhavingsplatform) zal dit wel bijgehouden worden.
•	Bijgevolg zal de relatie ‘verbalisant’ ook verwijderd worden uit de applicatiestandaard.
