### ISSUE TITLE
de relatie tussen feit en persoon wijkt af van de w3c provenance

### ISSUE THREAD

**Issue by gezever** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#5]
Feit - betrokkene - persoon/organisatie 
Graag prov:Activity - prov:wasAssociatedWith - prov:Agent relatie aub.
Er is geen enkele reden om van de w3c standaard af te wijken en zelf een nieuw model te maken.

**Comment by Vigetorix** [comment]
Beste Geert, 

We hebben enkele aanpassingen doorgevoerd in het model: 
- GepleegdFeit erft over van prov:Activity
- de classe prov::Agent is toegevoegd met tussen GepleegdFeit en prov::Agent een relatie 'betrokkene' (parentUri verwijzend naar wasAssociatedWith)
- GeregistreerdeOrganisatie en Persoon erven beiden over van prov::Agent

Laat maar weten wat je hiervan denkt.

**Comment by gezever** [comment]
@Vigetorix 
Dank je wel. Hoe kan ik de aanpassingen bekijken aub?
