### ISSUE TITLE
https://data.vlaanderen.be/ns/bestuurlijke-sancties#locatie niet zelf definieren

### ISSUE THREAD

**Issue by gezever** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#8]
In de https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap#GepleegdFeitShape wordt de range van de property locatie gedefinieerd als prov:Location
Waarom wordt hier zelf een property gemaakt ipv prov:atLocation te gebruiken?
 [
    shacl:class prov:Location;
    shacl:description "Locatie waar het Gepleegd Feit heeft plaatsgevonden.";
    shacl:name "locatie";
    shacl:path <https://data.vlaanderen.be/ns/bestuurlijke-sancties#locatie>
  ]

**Comment by Vigetorix** [comment]
Beste Geert, 

We hebben ook hier enkele aanpassingen gedaan aan het model: 
- Het attribuut locatie (met de uri van prov:atLocation) is toegevoegd aan GepleegdFeit
- Locatie is omgezet van een klasse naar een dataType waar de uri verwijst naar prov:Location. 
- De relaties met de andere klassen zoals Gebouw, Gebouweenheid, ... zijn weggedaan en los op het model gezet
- ap-usageNote-nl van Locatie bevat de informatie omtrent het gebruik van de bovenstaande klassen

Laat maar weten wat je hiervan denkt.

**Comment by gezever** [comment]
@Vigetorix 
prima
