### ISSUE TITLE
Uri voldoet niet aan vereisten van id/doc redirect of ns

### ISSUE THREAD

**Issue by gezever** [dimi-schepers/OSLOthema-bestuurlijkSanctieregister#9]
https://data.vlaanderen.be/shacl/bestuurlijk-sanctieregister-ap#GepleegdFeitShape

**Comment by bertvannuffelen** [comment]
Beste Geert,

idd, het is zo dat deze URIs (en in het algemeen deze in de SHACL files) niet voldoen aan de PURI vereisten. 

Dat komt omdat we hier over niet-normatieve documenten spreken waarbij we ons de vrijheid behouden om de SHACL shape over tijd anders in te vullen. 
Het zijn dus _technische_ URIs voor het gemak van de generatie, maar niet met als doel PURIs te zijn.

Er kan over na gedacht worden welke URIs hier zinvol zijn, maar dat moeten we ook naar het gebruik van de SHACL gaan kijken. Ik denk dat we hier met de gebruikers hun verwachtingen eens moeten afstemmen.

**Comment by gezever** [comment]
Dag Bert,

Ik zie geen reden om shapes niet te publiceren. (Omgeving doe dat wel https://data.omgeving.vlaanderen.be/id/nodeshape/chemische_stof ) Dat shapes niet normatief zouden zijn vind ik een vreemd. Voor mij maakt het een, soms moeilijk te begrijpen, UML model concreet en stelt het ons in staat om fouten uit het model te halen, zie bijvoorbeeld https://github.com/Informatievlaanderen/OSLOthema-bestuurlijkSanctieregister/issues/10. 
We kunnen de shapes gebruiken en parsen.
In die zin zijn de fouten die [hier](https://github.com/metadata101/dcat-ap1.1/issues/5) staan belangrijker.
